# Generated by Django 4.2.26 on 2025-11-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='perfiles/', verbose_name='imagen de perfil'),
        ),
    ]
