# Generated by Django 4.2.26 on 2025-11-28 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('matematicas', 'Matemáticas'), ('ciencias', 'Ciencias'), ('gramatica', 'Gramática'), ('ingles', 'Inglés')], max_length=20, verbose_name='tipo de examen')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de completado')),
                ('puntuacion', models.IntegerField(default=0, help_text='Puntuación obtenida en el examen', verbose_name='puntuación')),
                ('aprobado', models.BooleanField(default=False, help_text='Indica si el examen fue aprobado (≥10 aciertos)', verbose_name='aprobado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_completados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen Completado',
                'verbose_name_plural': 'Exámenes Completados',
                'ordering': ['-fecha_completado'],
                'unique_together': {('usuario', 'tipo_examen')},
            },
        ),
    ]
