# Generated by Django 4.2.26 on 2025-11-28 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_examencompletado'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('matematicas', 'Matemáticas'), ('ciencias', 'Ciencias'), ('gramatica', 'Gramática'), ('ingles', 'Inglés')], max_length=20, verbose_name='módulo')),
                ('numero_juego', models.IntegerField(help_text='Número del juego (1-5)', verbose_name='número de juego')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de completado')),
                ('puntuacion', models.IntegerField(default=0, help_text='Puntuación obtenida en el juego', verbose_name='puntuación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_completados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juego Completado',
                'verbose_name_plural': 'Juegos Completados',
                'ordering': ['-fecha_completado'],
                'unique_together': {('usuario', 'modulo', 'numero_juego')},
            },
        ),
    ]
